services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: individuals-keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    volumes:
      - ./individuals-api/resources/realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - app-network
      - keycloak-db-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8080"]                   # Used TCP healthcheck because 'curl' not found
      interval: 10s
      timeout: 5s
      retries: 10
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  keycloak-postgres:
    image: postgres:17
    container_name: keycloak-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data                       # To save state between container restarts
    networks:
      - keycloak-db-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  individuals-api:
    build:
      context: .
      dockerfile: individuals-api/Dockerfile
    container_name: individuals-api
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      LOG_LEVEL_TOKEN_SERVICE: DEBUG                                          # DEBUG/INFO -> with/without: (log example) 'User with [username=test@mail.ru] has logged in'.
      LOG_LEVEL_WEB_FILTER: DEBUG                                             # DEBUG/INFO -> with/without: (log example) 'Request received on [url=...] from [userId=...]'.
      KC_REALM: individuals                                                   # Name of the Keycloak realm used for authentication and user management.
      KC_BASE_URL: http://keycloak:8080                                       # Base URL of the Keycloak server.
      KC_CLIENT_ID: individuals-api                                           # Client ID registered in Keycloak for this service.
      KC_CLIENT_SECRET: 9nekCm9JrhldqeBx5bw00LIzIBRYve6l                      # Secret associated with the Keycloak client. Must be hidden in production env.
      KC_CONNECTION_TIMEOUT: 5000                                             # Timeout (in millis) for HTTP connections to the Keycloak server.
      KC_ADMIN_TOKEN_CACHING_TIME_IN_SEC: 290                                 # Admin token caching time. Must be less than the actual expires_in (expires_in = 300).
      PERSON_SERVICE_BASE_URL: http://person-service:8083                     # Base URL of the Person service.
      PERSON_SERVICE_CONNECTION_TIMEOUT: 5000                                 # Timeout (in millis) for HTTP connections to the Person service.
      PROMETHEUS_METRICS_EXPORT_ENABLED: false                                # Enable/disable export metrics by Prometheus (pull model).
      OTLP_METRICS_EXPORT_ENABLED: true                                       # Enable/disable export metrics to Tempo (push model).
      OTLP_METRICS_EXPORT_BATCH_SIZE: 10000                                   # Number of measurements per request. If more measurements are found, then multiple requests will be made.
      OTLP_METRICS_EXPORT_URL: http://alloy:4318/v1/metrics                   # URI of the OTLP server.
      OTLP_METRICS_EXPORT_STEP: 10s                                           # The step (i.e. frequency of reporting) for sending metrics.
      OTEL_TRACING_EXPORT_OTLP_ENDPOINT: http://alloy:4317                    # Url for export traces via OTLP/HTTP or OTLP/GRPC protocol.
      OTEL_TRACING_EXPORT_OTLP_PROTOCOL: GRPC                                 # Protocol for export traces.
      OTEL_TRACING_EXPORT_ENABLED: true                                       # Enable/disable export traces to Tempo (push model).
      OTEL_TRACING_PROPAGATION_TYPE: w3c                                      # Tracing context propagation type (W3C-specification).
      OTEL_TRACING_SAMPLING_PROBABILITY: 1.0                                  # 1.0 = 100% requests (default: 0.1 = 10%).
      OTEL_BSP_SCHEDULE_DELAY: 5000                                           # Used by OpenTelemetry SDK. If near real-time tracing -> 1000. If debug -> 500 (Как часто отправлять батч, millis)
      OTEL_BSP_MAX_EXPORT_BATCH_SIZE: 512                                     # Used by OpenTelemetry SDK. If high load -> 2048 (Максимум span’ов в одном запросе)
      OTEL_BSP_MAX_QUEUE_SIZE: 2048                                           # Used by OpenTelemetry SDK. If high load -> 8196 (Размер буфера в памяти, bytes)
      OTEL_BSP_EXPORT_TIMEOUT: 30000                                          # Used by OpenTelemetry SDK. Сколько ждать отправки (30 сек)
    depends_on:                                                               # Observability не должна блокировать бизнес-сервисы. Поэтому Grafana stack нет в depends_on
      person-service:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  person-service:
    build:
      context: .
      dockerfile: person-service/Dockerfile
    container_name: person-service
    expose:
      - "8083"
    environment:
      SERVER_PORT: 8083
      LOG_LEVEL_WEB_FILTER: DEBUG                                             # DEBUG/INFO -> with/without: (log example) 'Request received on [url=...]'.
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://person-postgres:5432/psp
      SQL_LOGGING_ENABLED: false                                              # Enable/disable SQL logging.
      FLYWAY_ENABLED: true                                                    # Enable/disable DB migrations.
      PROMETHEUS_METRICS_EXPORT_ENABLED: false                                # Enable/disable export metrics by Prometheus (pull model).
      OTLP_METRICS_EXPORT_ENABLED: true                                       # Enable/disable export metrics to Tempo (push model).
      OTLP_METRICS_EXPORT_BATCH_SIZE: 10000                                   # Number of measurements per request. If more measurements are found, then multiple requests will be made.
      OTLP_METRICS_EXPORT_URL: http://alloy:4318/v1/metrics                   # URI of the OTLP server.
      OTLP_METRICS_EXPORT_STEP: 10s                                           # The step (i.e. frequency of reporting) for sending metrics.
      OTEL_TRACING_EXPORT_OTLP_ENDPOINT: http://alloy:4317                    # Url for export traces via OTLP/HTTP or OTLP/GRPC protocol.
      OTEL_TRACING_EXPORT_OTLP_PROTOCOL: GRPC                                 # Protocol for export traces.
      OTEL_TRACING_EXPORT_ENABLED: true                                       # Enable/disable export traces to Tempo (push model).
      OTEL_TRACING_PROPAGATION_TYPE: w3c                                      # Tracing context propagation type (W3C-specification).
      OTEL_TRACING_SAMPLING_PROBABILITY: 1.0                                  # 1.0 = 100% requests (default: 0.1 = 10%).
      OTEL_BSP_SCHEDULE_DELAY: 5000                                           # Used by OpenTelemetry SDK. If near real-time tracing -> 1000. If debug -> 500 (Как часто отправлять батч, millis)
      OTEL_BSP_MAX_EXPORT_BATCH_SIZE: 512                                     # Used by OpenTelemetry SDK. If high load -> 2048 (Максимум span’ов в одном запросе)
      OTEL_BSP_MAX_QUEUE_SIZE: 2048                                           # Used by OpenTelemetry SDK. If high load -> 8196 (Размер буфера в памяти, bytes)
      OTEL_BSP_EXPORT_TIMEOUT: 30000                                          # Used by OpenTelemetry SDK. Сколько ждать отправки (30 сек)
    depends_on:                                                               # Observability не должна блокировать бизнес-сервисы. Поэтому Grafana stack нет в depends_on
      person-postgres:
        condition: service_healthy
    networks:
      - app-network
      - person-db-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s                                                           # Проверять каждые 10с
      timeout: 5s                                                             # Ждать ответ не дольше 5с
      retries: 5                                                              # Считать контейнер здоровым, только после 5 успешных проверок подряд
      start_period: 5s                                                        # Даём приложению 5с на запуск (миграции и т.д.)
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  person-postgres:
    image: postgres:17
    container_name: person-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: psp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - person_postgres_data:/var/lib/postgresql/data                         # To save state between container restarts
    networks:
      - person-db-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-psp
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"                                  # Allows POST /api/v1/write. See tempo-config.yaml → metrics_generator + Alloy будет писать сюда
      - "--enable-feature=exemplar-storage"                                   # В Grafana на графике latency появляются точки → кликаешь точку → попадаешь в trace
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infrastructure/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    depends_on:
      alertmanager:
        condition: service_healthy                                            # Это гарантирует, что при старте стека Prometheus сразу сможет отправлять алерты.
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  alertmanager:                                                               # Prometheus не отправляет алерты напрямую в Grafana — он использует Alertmanager как посредника.
    image: prom/alertmanager:v0.32.1
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    expose:
      - "9093"
    volumes:
      - alertmanager_data:/alertmanager
      - ./infrastructure/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9093/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  loki:
    image: grafana/loki:3.5.12
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./infrastructure/loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki                                                       # To save state between container restarts
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  tempo:
    image: grafana/tempo:2.10.4
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"                                                           # OTLP/HTTP — used by Grafana.
    expose:
      - "4317"                                                                # OTLP/gRPC — used by Collector. Optional: "4318:4318" - OTLP/HTTP
    environment:
      TEMPO_LOG_LEVEL: INFO                                                   # If INFO, to see the reception of traces
    volumes:
      - ./infrastructure/tempo/tempo-config.yaml:/etc/tempo.yaml:ro
      - tempo_data:/var/tempo                                                 # To save state between container restarts
    networks:
      - app-network
    depends_on:
      - prometheus                                                            # Просто порядок запуска, без healthcheck. Для async remote_write достаточно
    restart: unless-stopped
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  grafana:
    image: grafana/grafana:12.4.3                                             # Last - 13.0.1
    container_name: grafana-psp
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana                                         # To save state between container restarts
    networks:
      - app-network
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  alloy:
    image: grafana/alloy:v1.16.0
    container_name: alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    ports:
      - "12345:12345"
    expose:
      - "4317"                                                                # OTLP gRPC
      - "4318"                                                                # OTLP HTTP
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock                             # Linux/macOS (для Windows: '- //./pipe/docker_engine:/var/run/docker.sock')
      - alloy-data:/var/lib/alloy/data                                        # To save state between container restarts
    networks:
      - app-network
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_started
    restart: unless-stopped
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла


  nexus:
    image: sonatype/nexus3:3.89.1
    container_name: nexus-psp
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: false
      INSTALL4J_ADD_VM_PARAMS: "-Dnexus.onboarding.enabled=false -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - nexus-init-net
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status/writable" ]
      interval: 5s
      timeout: 10s
      retries: 40
    restart: unless-stopped
    logging:
      driver: "local"                                                         # driver: local или json-file полностью совместим с Alloy
      options:
        max-size: "10m"                                                       # Один файл логов максимум 10 MB
        max-file: "3"                                                         # Хранить максимум 3 файла

    # -Dnexus.onboarding.enabled=false - отключить wizard окошко
    # -Djava.util.prefs.userRoot=... — это способ обойти ошибки с правами на запись в /root/.java, которые возникают из-за того, что Nexus пытается сохранить флаг принятия EULA в системные prefs.
    # Т.к. EULA гарантированно принимаются через REST API в nexus_init.sh, то можно перенаправить prefs в доступную директорию (javaprefs), чтобы избежать предупреждений.


  nexus-init:
    image: alpine:3.23.3
    container_name: nexus-init-psp
    command: ["sh", "/scripts/nexus_init.sh"]
    environment:
      NEXUS_URL: http://nexus:8081
      NEW_NEXUS_PASSWORD: admin123
      NEW_NEXUS_USERNAME: admin123
    volumes:
      - ./infrastructure/nexus/scripts/nexus_init.sh:/scripts/nexus_init.sh:ro
      - ./infrastructure/nexus/schemas:/schemas:ro
      - nexus-data:/nexus-data
    networks:
      - nexus-init-net
    depends_on:
      nexus:
        condition: service_healthy
    init: true


volumes:
  keycloak_postgres_data:
  person_postgres_data:
  loki_data:
  tempo_data:
  grafana_data:
  alloy-data:
  alertmanager_data:
  nexus-data:


networks:
  app-network:
    driver: bridge
  keycloak-db-net:
    driver: bridge
  person-db-net:
    driver: bridge
  nexus-init-net:
    driver: bridge
