groups:
  - name: latency-alerts                                # 95% всех HTTP-запросов за последние 5 минут выполняются дольше 1 секунды
    rules:                                              # latency-alerts показывает «сколько ждал клиент»
      - alert: HighLatency
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_server_requests_milliseconds_bucket[5m])) by (le, service)
          ) > 1000
        for: 30s                                        # DEV -> 30s, PROD -> 2m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "Service {{ $labels.service }} latency is high"

  - name: tracing-alerts                                # latency из traces, а не HTTP метрик
    rules:                                              # tracing-alerts помогает найти медленные внутренние компоненты
      - alert: HighTraceLatency
        expr: |
          histogram_quantile(0.95, 
            sum(rate(traces_spanmetrics_latency_bucket[5m])) by (le, service)
          ) > 1
        for: 30s                                        # DEV -> 30s, PROD -> 2m
        labels:
          severity: warning
        annotations:
          summary: "High trace latency"
          description: "Service {{ $labels.service }} is slow"

  - name: tracing-errors                                # Алерт, если какой-то сервис падает
    rules:
      - alert: HighErrorRate
        expr: |
          (
          sum(rate(traces_spanmetrics_calls_total{status_code="STATUS_CODE_ERROR"}[5m])) by (service)
          /
          sum(rate(traces_spanmetrics_calls_total[5m])) by (service)
          ) * 100
          > 5
        for: 30s                                        # DEV -> 30s, PROD -> 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "An error rate of {{ $value | printf \"%.1f%%\" }} over the last 5 minutes (threshold: 5%)."
          impact: "Users may experience HTTP 5xx or internal failures."
          action: "Inspect Tempo traces and logs."


# Grafana -> Alerting -> Alert rules:
# Список правил:
#   - HighLatency
#   - HighTraceLatency
#   - HighErrorRate
# Статусы:
#   - Normal — всё ок,
#   - Pending — условие выполняется, но ещё не прошло 'for: 2m',
#   - Firing — алерт активен!

# latency-alerts:
#   - Берёт все временные ряды метрики http_server_requests_milliseconds_bucket,
#   - Группирует их по le (bucket) и service (individuals-api, person-service),
#   - Вычисляет 95-й перцентиль для каждого значения service отдельно,
#   - Сравнивает результат с 1 секундой.