global:
  scrape_interval: 15s                        # global metrics collection interval
  scrape_timeout: 10s                         # timeout when requesting metrics
  evaluation_interval: 15s                    # как часто считаются: alert rules и recording rules

scrape_configs:
  # ================================================================================================================== #
  # Prometheus (self-monitoring)                                                                                       #
  # ================================================================================================================== #
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  # ================================================================================================================== #
  # Individuals API                                                                                                    #
  # ================================================================================================================== #
  - job_name: 'individuals-api'
    metrics_path: '/actuator/prometheus'      # URL for collecting metrics
    static_configs:
      - targets: [ 'individuals-api:8082' ]     # docker-compose: service name (de facto: docker DNS -> container IP)
        labels:
          service: 'individuals-api'
          env: 'docker'
    basic_auth:
      username: PROMETHEUS
      password: "P5w9432nlg7y0q3b3g3h47810fm9aa0nc32"
    relabel_configs:
      - action: labeldrop                     # removing the "job" label (it's redundant)
        regex: ^job$

  # ================================================================================================================== #
  # Person Service                                                                                                     #
  # ================================================================================================================== #
  - job_name: 'person-service'
    metrics_path: '/actuator/prometheus'      # URL for collecting metrics
    static_configs:
      - targets: [ 'person-service:8083' ]      # docker-compose: service name (de facto: docker DNS -> container IP)
        labels:
          service: 'person-service'
          env: 'docker'
    basic_auth:
      username: PROMETHEUS
      password: "P5w9432nlg7y0q3b3g3h47810fm9aa0nc32"
    relabel_configs:
      - action: labeldrop                     # removing the "job" label (it's redundant)
        regex: ^job$

rule_files:
  - "alerts.yml"