global:
  scrape_interval: 15s                       # global metrics collection interval
  scrape_timeout: 10s                        # timeout when requesting metrics
  evaluation_interval: 15s                   # как часто считаются: alert rules и recording rules

storage:
  tsdb:
    out_of_order_time_window: 10m            # это позволит принимать немного "кривые" данные

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']     # для отправки алертов в Alertmanager

remote_write:
  - url: http://localhost:9090/api/v1/write  # Prometheus будет писать сюда свои метрики

scrape_configs:                              # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

rule_files:
  - "alerts.yml"