server:
  http_listen_port: 9080                                                            # === Порт для внутреннего HTTP API Promtail (не обязателен, но полезен для health-check) ===
  grpc_listen_port: 0                                                               # === gRPC отключён (не используется в данном сценарии) ===

positions:
  filename: /tmp/positions.yaml                                                     # === Файл, где Promtail хранит позицию чтения логов (чтобы не дублировать при перезапуске) ===

clients:
  - url: http://loki:3100/loki/api/v1/push                                          # === Адрес Loki, куда отправлять логи ===

scrape_configs:
  - job_name: docker                                                                # === Имя job'ы (произвольное) ===
    docker_sd_configs:
      - host: tcp://host.docker.internal:2375                                       # === ← для Windows. Специальный DNS-адрес Docker Daemon ===
#      - host: unix:///var/run/docker.sock                                          # === ← для Linux/macOS
        refresh_interval: 5s                                                        # === Как часто обновлять список контейнеров ===
    relabel_configs:                                                                # === Преобразование метаданных Docker в метки Loki ===
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service'] # === ФИЛЬТРАЦИЯ: оставляем только нужные сервисы ===
        regex: 'individuals-api|person-service'
        action: keep
      - source_labels: ['__meta_docker_container_name']                             # === Создаёт метку {container="individuals-api-1"} для фильтрации по имени контейнера ===
        regex: '/?(.+)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service'] # === Создаёт метку {service="individuals-api"} — основная метка для запросов в Grafana ===
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project'] # === Создаёт метку {project="payment-system"} для разных проектов ===
        target_label: 'project'

    # ===   1) Парсит строку лога.                                                  ===
    # ===   2) Извлекает traceId (он в логе ...[traceId,spanId]...).                ===
    # ===   3) Добавляет его как метку trace_id в Loki.                             ===
    # ===   4) Эта метка станет доступна для фильтрации в Grafana.                  ===
    # ===   Без этого:                                                              ===
    # ===      - Grafana не сможет связать логи и трейсы;                           ===
    # ===      - Кнопка «Show logs» в трейсе будет пустой.                          ===
    # ===   С этим:                                                                 ===
    # ===      - Можно кликнуть на span в Tempo → увидеть все логи этого запроса;   ===
    # ===      - Можно найти логи по trace_id в Grafana → Explore → Loki.           ===
#    pipeline_stages:
#      - regex:
#          expression: '.*\[(?P<trace_id>[a-f0-9]{32}),[a-f0-9]+\].*'                # === Извлекает 32-символьный hex-идентификатор между '[' и ',' — это traceId ===
#      - labels:
#          trace_id:                                                                 # === Добавляет извлечённое значение как метку trace_id в Loki. ===

    # ===    Чтобы можно было искать не только по trace_id, но и по span_id         ===
    # ===    Теперь можно фильтровать глубже. Enterprise-level                      ===
    pipeline_stages:
      - regex:
          expression: '.*\[(?P<trace_id>[a-f0-9]{32}),(?P<span_id>[a-f0-9]+)\].*'
      - labels:
          trace_id:
          span_id:

# NOTE:
# relabel_configs:source_labels + pipeline_stages:labels формируют label scope:
#    project   = "payment-system"
#    service   = "individuals-api"
#    container = "individuals-api-1"
#    trace_id  = "e28c93..."
#    span_id   = "e28c93..."

# Alloy - docs - https://grafana.com/docs/alloy/latest/?spm=a2ty_o01.29997173.0.0.4e0f55fbcClUf9

# Promtail использует Go (Golang) для обработки логов. Go поддерживает именованные группы захвата вида (?P<name>...).
