server:
  http_listen_port: 3200                               # UI (доступ из браузера) + сюда ходит Grafana.
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"                     # Приём OTLP по gRPC (для Alloy)
  log_received_spans:
    enabled: true                                      # Для PROD → false. Только для дебага. Включает запись в журнал каждого полученного фрагмента данных

ingester:                                              # Буферизует трейсы, влияет на latency появления в Grafana
  max_block_duration: 5m                               # Как часто сбрасывать блоки на диск
  trace_idle_period: 10s                               # Когда трейc считается завершённым

compactor:
  compaction:
    block_retention: 24h                               # Сколько хранить трейсы

storage:
  trace:
    backend: local                                     # Для PROD → S3/GCS/Azure Blob
    local:
      path: /tmp/tempo/blocks                          # Для PROD → /var/tempo/traces

query_frontend:
  max_outstanding_per_tenant: 2048                     # Лимит параллельных запросов. Если превышен: запросы начинают ждать или отклоняются. Важно, когда много пользователей Grafana и при heavy queries
  search:
    query_ingesters_until: 30m                         # До 30 минут → искать в ingester. После → искать в storage. Пересечение → искать в обоих

querier:                                               # Реально выполняет запросы frontend → querier
  max_concurrent_queries: 20                           # Сколько запросов реально выполняется. Если мало: очередь растёт. Если много: CPU умирает
  search:
    query_timeout: 30s                                 # Защита от огромных запросов и от зависаний
  frontend_worker:
    frontend_address: 127.0.0.1:9095                   # Optional: адрес интерфейса обработки запросов, к которому необходимо подключиться и который будет обрабатывать запросы.

metrics_generator:                                     # Из трейсов → метрики (service graph (кто кого вызывает), latency, RPS)
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal                     # Для PROD → /var/tempo/generator/wal
    remote_write:                                      # Отправляет метрики в Prometheus
      - url: http://prometheus:9090/api/v1/write       # Туда Tempo шлёт метрики (POST /api/v1/write)

overrides:
  defaults:
    ingestion:
      rate_limit_bytes: 10485760                       # 10MB/s. Лимит на ingestion. Если превышен → трейсы дропаются
      burst_size_bytes: 20971520                       # 20MB burst. Кратковременный “всплеск”. Это защита от: DDoS, багов в сервисах и runaway логирования
    metrics_generator:
      processors:
        - service-graphs                               # строит зависимости: service A → service B → service C
        - span-metrics                                 # Создаёт: latency, RPS и error rate

stream_over_http_enabled: true                         # Позволяет: стримить результаты поиска + быстрее отдавать большие трейсы
partition_ring_live_store: true                        # Оптимизация: масштабирование live_store. Важно при high load


########################################################################################################################

# DOCS: https://grafana.com/docs/tempo/latest/configuration/?spm=a2ty_o01.29997173.0.0.4e0f55fbjS6cDB

#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | server:                            | Настройки HTTP/gRPC сервера Tempo.                                                        |
#  |   http_listen_port: 3200           | UI (доступ из браузера) + сюда ходит Grafana.                                             |
#  |   grpc_listen_port: 9095           | UI (доступ из браузера) + сюда ходит Grafana.                                             |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | distributor:                       | Конфигурация приёмников (receivers) для входящих данных.                                  |
#  |   receivers:                       |                                                                                           |
#  |     otlp:                          | Использовать OpenTelemetry Protocol (OTLP).                                               |
#  |       protocols:                   |                                                                                           |
#  |         http:                      | Включить HTTP-эндпоинт для приёма OTLP.                                                   |
#  |           endpoint: "0.0.0.0:4318" | 4318 - порт для приёма OTLP по HTTP (используется Spring Boot)                            |
#  |         grpc:                      | (Опционально)                                                                             |
#  |           endpoint: "0.0.0.0:4317" | 4317 - порт для приёма OTLP по gRPC (не используется в Spring Boot по умолчанию).         |
#  |                                    | Актуально для Collector → Temp. Быстрее, чем http.                                        |
#  |   log_received_spans:              |                                                                                           |
#  |     enabled: true                  | true -> логирует КАЖДЫЙ span, который приходит в Tempo: received spanid=... traceid=...   |
#  |                                    | при нагрузке → тысячи логов в секунду. Ставить: dev -> true, prod -> false                |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | storage:                           | Где хранить трейсы.                                                                       |
#  |   trace:                           |                                                                                           |
#  |     backend: local                 | Хранить локально (внутри контейнера). Подходит для dev.                                   |
#  |     local:                         |                                                                                           |
#  |       path: /tmp/tempo/blocks      | Путь внутри контейнера для хранения блоков трассировок.                                   |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | compactor:                         | Настройки фоновой компактификации (объединение маленьких файлов в большие).               |
#  |   compaction:                      |                                                                                           |
#  |     block_retention: 24h           | Удалять трейсы старше 24ч. Для продакшена увеличьте (например, 720h = 30 дней).           |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | metrics_generator:                 | (Опционально) Генерация метрик из трассировок (например, latency, error rate)             |
#  |   registry:                        | и отправка их в Prometheus ч-з Remote Write API. Требует подключения Prometheus.          |
#  |     external_labels:               | Нужно ли это:                                                                             |
#  |       source: tempo                | Да, если хочешь использовать Service Graph или метрики на основе трейсов в Grafana.       |
#  |   storage:                         | Нет, если используешь Tempo только для просмотра трассировок.                             |
#  |     path: /tmp/tempo/generator/wal | Не используется, если нет Prometheus.                                                     |
#  |     remote_write:                                                                                                              |
#  |       - url: http://prometheus:9090/api/v1/write                                                                               |
#  |                                                                                                                                |
#  |   processors: ["service-graphs", "span-metrics"] - (optional) Вкл-ть Service Graph, чтобы видеть граф взаимодействия сервисов  |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | stream_over_http_enabled: true     | Tempo логирует каждый полученный span в свой stdout/stderr.                               |
#  |                                    | level=info ts=2026-04-15T12:00:00Z msg="received span" traceID=abc123... spanID=def456... |
#  |                                    | Зачем это нужно?                                                                          |
#  |                                    | Отладка интеграции: сразу видно, приходят ли данные от Spring Boot.                       |
#  |                                    | Проверка формата: убедиться, что OTLP-данные корректны.                                   |
#  |                                    | Мониторинг потока: нет ли дублей или пропусков.                                           |
#  |                                    | Как протестировать?                                                                       |
#  |                                    | docker compose up tempo -> Сделайте запрос -> Посмотрите логи Tempo ->                    |
#  |                                    | docker compose logs tempo -> Вы должны увидеть строки вида 'received span'.               |
#  +------------------------------------+-------------------------------------------------------------------------------------------+

#     Live Store — это механизм хранения «горячих» (ещё не сохранённых на диск) трассировок в памяти/WAL,
#     чтобы их можно было просматривать в реальном времени через Live Tail:
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | stream_over_http_enabled: true     | Позволяет: стримить результаты поиска + быстрее отдавать большие трейсы                   |
#  | partition_ring_live_store: true    | Оптимизация: масштабирование live_store. Важно при high load                              |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  |   live_store:                      | В контейнере Linux /tmp — стандартное место для временных данных.                         |
#  | ring:                              | При перезапуске контейнера всё содержимое /tmp теряется, что нормально для dev.           |
#  |   kvstore:                         | /var/tempo подразумевает постоянное хранение, как в production (часто монтируется volume).|
#  |     store: inmemory                | Если вы не монтируете volume из хоста, разницы в поведении нет, но /tmp                   |
#  | wal:                               | семантически правильнее для временных WAL-файлов.                                         |
#  |   path: /tmp/tempo/live-store/wal  |                                                                                           |
#  |                 или                |                                                                                           |
#  |   path: /var/tempo/live-store/wal  |                                                                                           |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
#  | querier:                           |                                                                                           |
#  |   query_live_store: true (old)     | ← КЛЮЧЕВОЙ ПАРАМЕТР - разрешение querier'у читать из Live Store. Если False, то Grafana   |
#  |                                    | не сможет получать данные из Live Store.                                                  |
#  |                                    | Tempo хранит данные в двух местах:                                                        |
#  |  query_frontend:                   | Хранилище: live_store	      - свежие трейсы (ещё не записаны в блоки)                     |
#  |    search:                         | Хранилище: storage (blocks) - уже сохранённые                                             |
#  |      query_ingesters_until (new)   | Без query_live_store:                                                                     |
#  |                                    |    - новые трейсы появляются с задержкой (пока ingester не сбросит блок)                  |
#  |                                    | С query_live_store: true                                                                  |
#  |                                    |    - Grafana видит трейсы почти сразу                                                     |
#  |   search:                          |                                                                                           |
#  |     query_timeout: 30s             | Максимальное время выполнения поискового запроса в Tempo                                  |
#  +------------------------------------+-------------------------------------------------------------------------------------------+
