# ==================================================================================================================== #
# BASE config                                                                                                          #
# ==================================================================================================================== #
server:
  port: 8081

info:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}

# ==================================================================================================================== #
# APPLICATION config                                                                                                   #
# ==================================================================================================================== #
individuals-api:
  swagger:
    local-server: http://localhost
  keycloak:
    realm: individuals
    base-url: http://localhost:8080
    client-id: individuals-api
    client-secret: 9nekCm9JrhldqeBx5bw00LIzIBRYve6l
    connection-timeout: 5000

# ==================================================================================================================== #
# SPRING config                                                                                                        #
# ==================================================================================================================== #
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${individuals-api.keycloak.base-url}/realms/${individuals-api.keycloak.realm}/protocol/openid-connect/certs

# ==================================================================================================================== #
# METRICS config                                                                                                       #
# ==================================================================================================================== #
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    health:
      show-details: ALWAYS
