# ==================================================================================================================== #
# BASE config                                                                                                          #
# ==================================================================================================================== #
server:
  port: ${SERVER_PORT}

info:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}

logging:
  level:
    by.itbatia.psp.individualsapi.service.impl.TokenServiceImpl: ${LOG_LEVEL_TOKEN_SERVICE}

# ==================================================================================================================== #
# APPLICATION config                                                                                                   #
# ==================================================================================================================== #
individuals-api:
  swagger:
    local-server: http://localhost
  keycloak:
    realm: ${KC_REALM}
    base-url: ${KC_BASE_URL}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    connection-timeout: ${KC_CONNECTION_TIMEOUT}
    admin-token-caching-time-in-sec: ${KC_ADMIN_TOKEN_CACHING_TIME_IN_SEC}
  person-service-client:
    base-url: ${PERSON_SERVICE_BASE_URL}
    connection-timeout: ${PERSON_SERVICE_CONNECTION_TIMEOUT}

# ==================================================================================================================== #
# SPRING config                                                                                                        #
# ==================================================================================================================== #
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${individuals-api.keycloak.base-url}/realms/${individuals-api.keycloak.realm}/protocol/openid-connect/certs

# ==================================================================================================================== #
# METRICS config                                                                                                       #
# ==================================================================================================================== #
management:
  prometheus:
    metrics:
      export:
        enabled: ${EXPORT_METRICS_ENABLED}
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    health:
      show-details: ALWAYS
