# ==================================================================================================================== #
# BASE config                                                                                                          #
# ==================================================================================================================== #
server:
  port: ${SERVER_PORT}

info:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}

logging:
  level:
    by.itbatia.psp.individualsapi.service.impl.TokenServiceImpl: ${LOG_LEVEL_TOKEN_SERVICE}
    by.itbatia.psp.individualsapi.config.WebFilterConfig: ${LOG_LEVEL_WEB_FILTER_CONFIG}
    by.itbatia.psp.individualsapi.util.OtelUtil: ${LOG_LEVEL_OTEL_UTIL}
    by.itbatia.psp.individualsapi.filter.LoggingWebFilter: ${LOG_LEVEL_WEB_FILTER}

# ==================================================================================================================== #
# APPLICATION config                                                                                                   #
# ==================================================================================================================== #
individuals-api:
  swagger:
    local-server: http://localhost
  keycloak:
    realm: ${KC_REALM}
    base-url: ${KC_BASE_URL}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    connection-timeout: ${KC_CONNECTION_TIMEOUT}
    admin-token-caching-time-in-sec: ${KC_ADMIN_TOKEN_CACHING_TIME_IN_SEC}
  person-service-client:
    base-url: ${PERSON_SERVICE_BASE_URL}
    connection-timeout: ${PERSON_SERVICE_CONNECTION_TIMEOUT}

# ==================================================================================================================== #
# SPRING config                                                                                                        #
# ==================================================================================================================== #
spring:
  application:
    name: ${info.application.name}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${individuals-api.keycloak.base-url}/realms/${individuals-api.keycloak.realm}/protocol/openid-connect/certs

# ==================================================================================================================== #
# METRICS + OPENTELEMETRY config                                                                                       #
# ==================================================================================================================== #
management:
  prometheus:
    metrics:
      export:
        enabled: ${PROMETHEUS_METRICS_EXPORT_ENABLED}
  endpoints:
    web:
      exposure:
        include: prometheus, health
  otlp:
    metrics:
      export:
        enabled: ${OTLP_METRICS_EXPORT_ENABLED}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACING_EXPORT_OTLP_ENDPOINT}
    resource-attributes:
      service.name: ${info.application.name}
  tracing:
    export:
      enabled: ${TRACING_EXPORT_ENABLED}
    propagation:
      type: ${TRACING_PROPAGATION_TYPE}
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY}
