{
 "title": "individuals-api",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Общее количество логинов и регистраций (за последний час)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(login_total{service=\"individuals-api\", status=\"success\"}[1h]))",
     "legendFormat": "Успешные логины"
    },
    {
     "expr": "round(increase(login_total{service=\"individuals-api\", status=\"fail\"}[1h]))",
     "legendFormat": "Неудачные логины"
    },
    {
     "expr": "round(increase(registration_total{service=\"individuals-api\", status=\"success\"}[1h]))",
     "legendFormat": "Успешные регистрации"
    },
    {
     "expr": "round(increase(registration_total{service=\"individuals-api\", status=\"fail\"}[1h]))",
     "legendFormat": "Неудачные регистрации"
    }
   ]
  },
  {
   "title": "Все логи сервиса",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service=\"individuals-api\"}"
    }
   ]
  },
  {
   "title": "Доля успешных логинов и регистраций (за последний час)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(increase(login_total{status=\"success\"}[1h]))\r\n  /\r\n  sum(increase(login_total[1h]))\r\n)\r\n* 100",
     "legendFormat": "Доля успешных логинов"
    },
    {
     "expr": "(\r\n  sum(increase(registration_total{status=\"success\"}[1h]))\r\n  /\r\n  sum(increase(registration_total[1h]))\r\n)\r\n* 100",
     "legendFormat": "Доля успешных регистраций"
    }
   ]
  },
  {
   "title": "Ошибки и предупреждения",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service=\"individuals-api\"} |~ \"(ERROR|WARN)\""
    }
   ]
  },
  {
   "title": "Средняя латентность Keycloak-вызовов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(kc_login_latency_seconds_sum{service=\"individuals-api\", status=\"success\"}[5m])\r\n/\r\nrate(kc_login_latency_seconds_count{service=\"individuals-api\", status=\"success\"}[5m])\r\nunless\r\nrate(kc_login_latency_seconds_count{service=\"individuals-api\", status=\"success\"}[5m]) <= 0",
     "legendFormat": "Среднее время логина в Keycloak"
    },
    {
     "expr": "rate(kc_registration_latency_seconds_sum{service=\"individuals-api\", status=\"success\"}[5m])\r\n/\r\nrate(kc_registration_latency_seconds_count{service=\"individuals-api\", status=\"success\"}[5m])\r\nunless\r\nrate(kc_registration_latency_seconds_count{service=\"individuals-api\", status=\"success\"}[5m]) <= 0",
     "legendFormat": "Среднее время регистрации в Keycloak"
    }
   ]
  },
  {
   "title": "Сравнение: HTTP vs Keycloak latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{service=\"individuals-api\", uri=\"/api/v1/auth/login\", status=\"200\"}[5m])\r\n/\r\nrate(http_server_requests_seconds_count{service=\"individuals-api\", uri=\"/api/v1/auth/login\", status=\"200\"}[5m])",
     "legendFormat": "HTTP latency (login endpoint)"
    },
    {
     "expr": "rate(kc_login_latency_seconds_sum{service=\"individuals-api\", status=\"success\"}[5m])\r\n/\r\nrate(kc_login_latency_seconds_count{service=\"individuals-api\", status=\"success\"}[5m])",
     "legendFormat": "Keycloak latency (login)"
    }
   ]
  },
  {
   "title": "График частоты ошибок",
   "type": "timeseries",
   "description": "Показывает, сколько ошибок в минуту",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({service=\"individuals-api\"} |= \"ERROR\" [5m])",
     "legendFormat": "ERROR"
    }
   ]
  }
 ]
}