# ==================================================================================================================== #
# BASE config                                                                                                          #
# ==================================================================================================================== #
server:
  port: ${SERVER_PORT}

info:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}
