# ==================================================================================================================== #
# BASE config                                                                                                          #
# ==================================================================================================================== #
server:
  port: 8083

# ==================================================================================================================== #
# APPLICATION config                                                                                                   #
# ==================================================================================================================== #


# ==================================================================================================================== #
# METRICS config                                                                                                       #
# ==================================================================================================================== #

