# ==================================================================================================================== #
# BASE config                                                                                                          #
# ==================================================================================================================== #
server:
  port: 8083

# ==================================================================================================================== #
# SPRING config                                                                                                        #
# ==================================================================================================================== #
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/psp
  jpa:
    show-sql: false
  flyway:
    enabled: true

# ==================================================================================================================== #
# METRICS + OPENTELEMETRY config                                                                                       #
# ==================================================================================================================== #
management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true            # Включает bucket'ы для HTTP-метрик
  prometheus:
    metrics:
      export:
        enabled: false                        # Отключить Prometheus scraping
  endpoints:
    web:
      exposure:
        include: health                       # Только для health check
  otlp:                                       # Экспорт метрик через OTLP в Alloy
    metrics:
      export:
        enabled: true
        batch-size: 10000
        url: http://localhost:4318/v1/metrics # http://alloy:4318/v1/metrics
        step: 10s                             # Интервал отправки OTLP-метрик
  opentelemetry:                              # Экспорт traces через OTLP в Alloy
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4317     # http://alloy:4317
          transport: GRPC
    resource-attributes:
      service.name: ${info.application.name}  # здесь будет название сервиса
  tracing:
    export:
      enabled: true
    propagation:
      type: w3c
    sampling:
      probability: 1.0

