# ==================================================================================================================== #
# BASE config                                                                                                          #
# ==================================================================================================================== #
server:
  port: ${SERVER_PORT}

info:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}

# ==================================================================================================================== #
# SPRING config                                                                                                        #
# ==================================================================================================================== #
spring:
  application:
    name: ${info.application.name}
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    show-sql: ${SQL_LOGGING_ENABLED}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   # Optional.
        format_sql: true                                   # Beautiful SQL formatting in logs.
  flyway:
    enabled: ${FLYWAY_ENABLED}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration

# ==================================================================================================================== #
# METRICS + OPENTELEMETRY config                                                                                       #
# ==================================================================================================================== #
management:
  prometheus:
    metrics:
      export:
        enabled: ${PROMETHEUS_METRICS_EXPORT_ENABLED}
  endpoints:
    web:
      exposure:
        include: prometheus, health
  otlp:
    metrics:
      export:
        enabled: ${OTLP_METRICS_EXPORT_ENABLED}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACING_EXPORT_OTLP_ENDPOINT}
    resource-attributes:
      service.name: ${info.application.name}
  tracing:
    export:
      enabled: ${TRACING_EXPORT_ENABLED}
    propagation:
      type: ${TRACING_PROPAGATION_TYPE}
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY}
